name: Crystal CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: "crystal: ${{ matrix.crystal }}, stable: ${{ matrix.stable }}"
    continue-on-error: ${{ !matrix.stable }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        crystal: [latest]
    runs-on: ${{matrix.os}}

    steps:
    - name: Install Crystal
      uses: oprypin/install-crystal@v1
      with:
        crystal: ${{ matrix.crystal }}
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: crystal spec -Dpreview_mt --order random --error-on-warnings
#    - name: Run bulid
#      run: shards build -Dpreview_mt
    - name: Run format
      run: crystal tool format --check

